### ISSUE TITLE
RoadMap : Livrables

### ISSUE THREAD

**Issue by CinquinAndy** [CinquinAndy/i1-mspr-data#3]
- [ ] Livrable : Justification du choix de la zone géographique
- [ ] Livrable : Choix des critères, justification
- [ ] Livrable : La démarche suivie et les méthodes employées
- [ ] Livrable : Un Modèle Conceptuel de Données
- [ ] Livrable : Les modèles testés
- [ ] Livrable : Les résultats du modèle choisi
- [ ] Livrable : Les visualisations
- [ ] Livrable : Accuracy (pouvoir prédictif du modèle)
- [ ] Livrable : Les réponses aux questions posées dans les exemples d’indicateurs d’analyse ci-dessus (vous pouvez également ajouter d’autres indicateurs pertinents d’analyse).
- [ ] Livrable : Un jeu de données nettoyé, normalisé et optimisé
- [ ] Livrable : Le choix du format est libre (SQL ou NoSQL)
- [ ] Livrable : Votre code, propre et commenté
